ROWS = 8
COLS = 8

TILE_SIZE = 71

SCREEN_WIDTH = COLS * TILE_SIZE
SCREEN_HEIGHT = ROWS * TILE_SIZE

PIECE_RADIUS = 0.76 * TILE_SIZE / 2
QUEEN_RADIUS = 8
PIECE_HEIGHT = 0.01 * SCREEN_HEIGHT

LIGHT_PIECE_COLOR = (238, 90, 90)
LIGHT_PIECE_SHADOW = tuple(3 * x / 4 for x in LIGHT_PIECE_COLOR)

DARK_PIECE_COLOR = (87, 74, 74)
DARK_PIECE_SHADOW = tuple(3 * x / 4 for x in DARK_PIECE_COLOR)

DARK_TILE_COLOR = (125, 149, 94)
LIGHT_TILE_COLOR = (238, 238, 212)
ACTIVE_TILE_COLOR = tuple(2 * x / 3 for x in DARK_TILE_COLOR)
