from enum import Enum


class TimeOutException(Exception):
    pass


ROWS = 8
COLS = 8

TILE_SIZE = 71

SCREEN_WIDTH = COLS * TILE_SIZE
SCREEN_HEIGHT = ROWS * TILE_SIZE

PIECE_RADIUS = 0.76 * TILE_SIZE / 2
QUEEN_RADIUS = 8
PIECE_HEIGHT = 0.01 * SCREEN_HEIGHT

LIGHT_PIECE_COLOR = (232, 190, 145)
LIGHT_PIECE_SHADOW = tuple(0.75 * x for x in LIGHT_PIECE_COLOR)

DARK_PIECE_COLOR = (70, 48, 34)
DARK_PIECE_SHADOW = tuple(0.75 * x for x in DARK_PIECE_COLOR)

DARK_TILE_COLOR = (95, 65, 42)
LIGHT_TILE_COLOR = (169, 123, 83)
ACTIVE_TILE_COLOR = tuple(0.4 * x for x in DARK_TILE_COLOR)

MAIN_MENU_BG_COLOR = (127, 75, 42)

# Fonts:
HEADER_FONT_SIZE = 72
HEADER_FONT_COLOR = (244, 222, 184)
HEADER_X = 96
HEADER_Y = 75

BUTTON_FONT_SIZE = 30
BUTTON_FONT_COLOR = (241, 214, 167)
BUTTON_PVP_X = 180
BUTTON_PVP_Y = 360
BUTTON_PVC_Y = BUTTON_PVP_Y + 68
BUTTON_PVC_X = 200

GAME_OVER_FONT_SIZE = 48
GAME_OVER_FONT_COLOR = (241, 214, 167)

AGAIN_Y = BUTTON_PVP_Y
AGAIN_X = 225


class StateResult(Enum):
    DRAW = 1
    PLAYING = 2
    LIGHT_WON = 3
    DARK_WON = 4


class GameState(Enum):
    MAIN_MENU = 1
    PLAYING = 2
    ENDING = 3
    GAME_OVER = 4


class GameMode(Enum):
    PLAYER_VS_PLAYER = 1
    PLAYER_VS_COMPUTER = 2


def get_selected_tile(mouse_pos):
    x, y = mouse_pos
    x //= TILE_SIZE
    y //= TILE_SIZE
    return y * COLS + x
